export type Tutor = {
	id: string | number;
	image?: string;
	name: string;
	fullName?: string;
	studentId?: string;
	email?: string;
	role?: string;
	faculty?: string;
	subject: string;
	department: string;
	match?: string;
	slots?: { time: string; mode: string; remaining?: string }[];
	fullAvailability?: string[];
	status?: string;
	expertise?: string;
	detailedExpertise?: string;
	preferences?: string;
	detailedPreferences?: string;
	sessionsCompleted?: number;
	averageRating?: number;
	feedbacks?: { id: number; rating: number; comment: string; date: string }[];
	tutorId?: string;
	eduMail?: string;
	maxLoad?: number;
	currentLoad?: number;
	availability?: any;
	profileSummary?: string;
};
