export type Tutor = {
  id: string | number;
  tutorId?: string;
  name: string;
  fullName?: string;
  faculty?: string;
  department?: string;
  email?: string;
  eduMail?: string;
  subject: string;
  status?: string;
  slots?: { time: string; mode: string; remaining?: string }[];
  image?: string;
  role?: string;
  studentId?: string;
  feedbacks?: { id: number; rating: number; comment: string; date: string }[];
  detailedExpertise?: string;
  detailedPreferences?: string;
  sessionsCompleted?: number;
  averageRating?: number;
  match?: string | number;
  preferences?: any;
  expertise?: string[];
  workload?: { current: number; max: number };
  maxLoad?: number;
  currentLoad?: number;
  availability?: any;
  fullAvailability?: string[];
  profileSummary?: string;
};
